services:
  db:
    image: postgres:16
    container_name: incident_db
    environment:
      POSTGRES_DB: incidentdb
      POSTGRES_USER: incident_user
      POSTGRES_PASSWORD: incident_pass
    ports:
      - "5433:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: incident_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db

  app:
    build: .
    container_name: incident_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/incidentdb
      SPRING_DATASOURCE_USERNAME: incident_user
      SPRING_DATASOURCE_PASSWORD: incident_pass